### ISSUE TITLE
Beispielanwendung "springender Punkt"

### ISSUE THREAD

**Issue by suchja** [LernMoment/csharp-uebungskit#1]
@gustda Auch wenn im *csharp-canvas* bereits Beispielanwendungen enthalten sind, sollten wir hier auch welche anbieten, oder?

Ich bin der Ansicht, dass die Zielgruppe für dieses Projekt eine andere ist als beim *chsarp-canvas*. In diesem Projekt geht es darum, dass (hauptsächlich Einsteiger) die eine Übung machen wollen dies schnell umsetzen können. Daher wäre es gut ein kleines Beispiel und eine Beschreibung zu haben.

Was hältst du davon den hüpfenden i-Punkt hier zu integrieren? Eine Alternative wäre ein separates Projekt als Beispiel zu erstellen. Allerdings frage ich mich ob das nicht eher verwirrt, weil es dann so viele Projekte gibt.

**Comment by suchja** [comment]
Bitte Zusammen mit #2 bearbeiten!

**Comment by gustda** [comment]
Ich fände eine leeres Projekt ganz gut, damit man nichts löschen muss, um etwas eigenes zu machen, vielleicht als Beispiel Branch? Ob das aber der reine Weg ist, weiß ich nciht, fände ich halbwegs unsauber, aber vielleicht über Releases, so dass sich jeder auch noch das Leere Übungskit ziehen kann.

**Comment by suchja** [comment]
@gustda Dein Argument, dass es ein leeres Projekt gibt finde ich gut!

Wenn ich es jetzt richtig sehe, dann hast du die Änderungen in *master* gemacht und somit kommt das Projekt automatisch mit dem "hüpfenden I".
Ich werde das mal tatsächlich in einen Branch schieben und in der Erklärung passend verlinken.

**Comment by gustda** [comment]
Ich habe das jetzt über Releases gelöst, war das nicht deine Idee dazu?

**Comment by suchja** [comment]
Na klar! Habe ich nicht richtig hingeschaut. Hatte nur in die Datei [DrawingArea.cs](https://github.com/LernMoment/csharp-uebungskit/blob/916b62631d7057a9dfafa80789aaee11e7588e23/csharp-uebungskit/DrawingArea.cs#L40) geschaut und den Code für das springende-I gesehen.

Für die einfachere Wartung denke ich, dass es Sinn macht im *master* Branch nicht den Code für das springende-I zu haben. Was passiert, wenn es eine neue Version des Canvas gibt? Dann sollten wir ja beide Varianten updaten und neue release, oder?

**Comment by gustda** [comment]
Damit haben wir das jetzt in zwei Branches. Kannst du mir helfen den Pullrequest oder die aufforderung dazu los zu werden?

**Comment by suchja** [comment]
Ich denke dieses hier ist abgeschlossen, oder @gustda ?
