### ISSUE TITLE
"Hello World" dokumentieren

### ISSUE THREAD

**Issue by suchja** [LernMoment/csharp-uebungskit#2]
@gustda um den Einstieg für Übungswillige zu verbessern, wäre es hilfreich, wenn beispielsweise im *README.md* ein paar Schritte dokumentiert sind was man machen muss um ein erstes Programm mit diesem Übungskit zu erstellen!

Beispielsweise könntest du beschreiben wie ein hüpfender i-Punkt erstellt werden kann (siehe auch #1). Dabei stellt sich dann gerade die Frage ob es überhaupt nötig ist die Beispielanwendung wie in #1 beschrieben zu erstellen. Vielleicht reicht diese Beschreibung schon aus?

**Comment by gustda** [comment]
Mit #1 gemeinsam gelöst
